name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow when a new tag starting with 'v' (e.g., 'v1.0.0') is pushed.

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the environment to run the job on.

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code in your repository.

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4  # This action sets up Python in the specified version.
        with:
          python-version: '3.8'  # Specify the Python version you want (e.g., 3.8, 3.9).

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to the latest version.
          pip install setuptools wheel twine  # Installs build tools: setuptools, wheel, and twine.

      # Step 4: Build the package
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel  # Builds the source distribution and wheel file.

      # Step 5: Upload the package to PyPI
      - name: Upload package to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Your PyPI username, stored as a secret in GitHub.
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Your PyPI password or token, stored as a secret in GitHub.
        run: |
          pip install twine  # Ensure twine is installed.
          twine upload dist/*  # Uploads the built package files to PyPI.
